### PR TITLE
Latest fixes in regards to two issues

### PR DESCRIPTION
**Pull request by coenvlietstra**

### CODE REVIEW

**Comment by Psycoguana** [comment]
Hey, thanks a lot for your PR! 👋

Would you mind adding a few changes?

* When catching the utf-8 error, a simple `except` is too greedy, it will catch everything, even a `KeyboardInterrupt`. Change it to: `except UnicodeDecodeError:`

* Instead of wrapping a bunch of code inside `if hasattr(sub, 'url'):`, do it like this and you won't need to indent so much code:
```python
if not hasattr(sub, 'url'):
    continue
```

* `warnings.filterwarnings('ignore')` is there on purpose, pushshift warnings are annoying.

I don't know what the rest of your changes do. Please do one commit per fix and use more descriptive commit messages.

And again, thanks a lot for your interest on the repo and the PR! 😊

**Comment by coenvlietstra** [comment]
Whoa! Thank you for the quick reply and wonderful feedback.  I will make these changes and do a proper comment etc for the next one.  Should be later the afternoon

**Comment by coenvlietstra** [comment]
- [x]  When catching the utf-8 error, a simple except is too greedy, it will catch everything, even a KeyboardInterrupt. Change it to: except UnicodeDecodeError:
- [x] instead of wrapping a bunch of code inside if hasattr(sub, 'url'):, do it like this and you won't need to indent so much code
- [x] warnings.filterwarnings('ignore') is there on purpose, pushshift warnings are annoying.

Cleaned up the code, only commits are in regards to these three issues and have been corrected as you requested.

**Review by Psycoguana — CHANGES_REQUESTED** [review]
Hey! Looks good, just one thing. On line 136 it's still `if hasattr(sub, 'url'):`, which will make the script ignore every submission which has a url attribute, we want the opposite. Change it to: `if not hasattr(sub, 'url'):`

I think the rest looks good to go!

I also moved this to a dev branch just in case.

**Comment by coenvlietstra** [comment]
🤦  Fixed, thank you for all your feedback, etc!

**Review by Psycoguana — CHANGES_REQUESTED** [review]
Sorry I didn't catch this before, but on line 1 you import ast? That's not necessary, remove that and I'll merge it into the dev branch :)

**Comment by coenvlietstra** [comment]
Hi

Its been removed as requested :)

**Comment by Psycoguana** [comment]
Merged, thanks!

**Pull request merged**
